### PR TITLE
Update Bugsnag library to latest version

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This updates the Bugsnag library to the latest version. As a part of updating, the deprecated method call of `setEntity` has been replaced with `addToTab` which should create a new tab with new keys and the corresponding value that should be visible within the error details in the Bugsnag dashboard.

#### Old Bugsnag error detail

Screen Shot 2021-06-23 at 8 51 11 AM

#### New Bugsnag error detail

Screen Shot 2021-06-23 at 11 06 13 AM

### CODE REVIEW

**Review by br648 — APPROVED** [review]
LGTM

**Comment by binh-dam-ibigroup** [comment]
@evansiroky Your last commit https://github.com/ibi-group/otp-middleware/pull/146/commits/2f6de77eb27188dae13a6077f13ecb21fb4a3024 is breaking the build.

**Comment by evansiroky** [comment]
> @evansiroky Your last commit [2f6de77](https://github.com/ibi-group/otp-middleware/commit/2f6de77eb27188dae13a6077f13ecb21fb4a3024) is breaking the build.

I'm not sure what was causing some flaky tests, but I have reran the Github Actions and it's working now.

**Comment by evansiroky** [comment]
@br648, I re-requested a review since I added another commit since your approval.

**Review by binh-dam-ibigroup — APPROVED** [review]

**Review by br648 — APPROVED** [review]
Still LGTM!

**Review by landonreed — APPROVED** [review]

**Pull request merged**
